New Master upload.
Updated all files with current Piratebox release 1.1.4

diff --git a/publicbox/init.d/publicbox b/publicbox/init.d/publicbox
--- a/publicbox/init.d/publicbox
+++ b/publicbox/init.d/publicbox
@@ -50,16 +50,14 @@ export PYTHONPATH=:$PYTHONPATH:$PUBLICBOX_PYTHONPATH
 # Some things that run always
 touch /var/lock/publicbox
 
-if [ -f $CONF ]
-then
+if [ -f $CONF ]; then
    . $CONF 
 else 
    log_failure_msg "Configuration file not found"
    exit 1
 fi
 
-if [ -f $PUBLICBOX/conf/init_done ]
-then
+if [ -f $PUBLICBOX/conf/init_done ]; then
    INIT=OK
 else
    $PUBLICBOX/bin/hooks/hook_pre_init.sh  "$CONF"
@@ -71,7 +69,7 @@ fi
 #Recreate the content folder, if it was deleted.
 #But only if it does not already exist.
 #This can be any time.
-if [ ! -d  $WWW_CONTENT ] ; then
+if [ ! -d  $WWW_CONTENT ]; then
 	$PUBLICBOX/bin/install_publicbox.sh "$CONF" content
 fi
 
@@ -80,69 +78,60 @@ CMD_DNSMASQ="-x $PIDFILE_DNSMASQ -C $CONF_DNSMASQ "
 
 # Carry out specific functions when asked to by the system
 case "$1" in
-start)
-log_daemon_msg "Starting script publicbox "
-echo ""
+	start)
+	log_daemon_msg "Starting script publicbox "
+	echo ""
 
 # Generate hosts & dnsmasq file
-$PUBLICBOX/bin/generate_config_files.sh  "$CONF"
-    
-$PUBLICBOX/bin/hooks/hook_publicbox_start.sh  "$CONF"
+	$PUBLICBOX/bin/generate_config_files.sh  "$CONF"
+	    
+	$PUBLICBOX/bin/hooks/hook_publicbox_start.sh  "$CONF"
 
-echo "Empty tmp folder"
-find   $PUBLICBOX/tmp/*  -exec rm {} \;
+	echo "Empty tmp folder"
+	find   $PUBLICBOX/tmp/  -exec rm {} \;
 
-if [ "$CUSTOM_DIRLIST_COPY" = "yes" ]
-then
-	echo "Copy over directory design files"
-	$PUBLICBOX/bin/distribute_files.sh $SHARE_FOLDER/Shared
-fi
+	if [ "$CUSTOM_DIRLIST_COPY" = "yes" ]; then
+		echo "Copy over directory design files"
+		$PUBLICBOX/bin/distribute_files.sh $SHARE_FOLDER/Shared
+	fi
 
-if [ "$PBX_JSON_GENERATION" = "yes" ]
-then
-	$PUBLICBOX_FOLDER/bin/json_generation.sh  $CONF 
-fi
+	if [ "$PBX_JSON_GENERATION" = "yes" ]; then
+		$PUBLICBOX_FOLDER/bin/json_generation.sh  $CONF 
+	fi
 
-if [ "$DO_IW" = "yes" ]
-then
-	log_daemon_msg " Setting up Interface (iw) "
-	iw $PHY_IF interface add $INTERFACE type managed
-fi
+	if [ "$DO_IW" = "yes" ]; then
+		log_daemon_msg " Setting up Interface (iw) "
+		iw $PHY_IF interface add $INTERFACE type managed
+	fi
 
-if [ "$PROBE_INTERFACE" = yes ]
-then
-	log_daemon_msg "  Probing wlan"
+	if [ "$PROBE_INTERFACE" = yes ]; then
+		log_daemon_msg "  Probing wlan"
 #Setting up WLAN Interface
-	publicbox_setup_wlan.sh  $CONF probe
-fi
-if  [ $? -ne 0 ]
-then
-	log_failure_msg "failed probe Interface"
-else
+		publicbox_setup_wlan.sh  $CONF probe
+	fi
+	if  [ $? -ne 0 ]; then
+		log_failure_msg "failed probe Interface"
+	else
 
 # Only  activate
-	if  [ "$USE_APN" =  "yes" ]
-	then
+	if  [ "$USE_APN" =  "yes" ]; then
 		log_daemon_msg  "Starting hostap... "
 		start-stop-daemon -m --start --background --pidfile $PIDFILE_HOSTAPN  --exec /usr/sbin/hostapd --  $CONF_APN
 		log_end_msg $?
 	fi
 
-	if [ "$DO_IFCONFIG" = yes ]
-	then
+	if [ "$DO_IFCONFIG" = yes ]; then
 		log_daemon_msg "  Setting up wlan"
 #Setting up WLAN Interface
 		publicbox_setup_wlan.sh  $CONF start
-		if  [ $? -ne 0 ]
-		then
+		if  [ $? -ne 0 ]; then
 			log_failure_msg "failed setting up Interface"
 			exit 99
 		fi
 	fi
 
 #BRIDGE
-	if [ "$DO_BRIDGE" = "yes"  ]
-	then
+	if [ "$DO_BRIDGE" = "yes"  ]; then
 		log_daemon_msg  "Adding $INTERFACE to bridge $BRIDGE //  brctl addif $BRIDGE  $INTERFACE "
 		sleep 1
 		BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
@@ -150,8 +139,7 @@ else
 		log_end_msg $?
 	fi
 
-	if [ "$USE_DNSMASQ" = "yes" ]
-	then
+	if [ "$USE_DNSMASQ" = "yes" ]; then
 		log_daemon_msg  "Starting dnsmasq... "
 # pidfile is written by dnsmasq
 		start-stop-daemon --start --quiet --exec /usr/sbin/dnsmasq  --  $CMD_DNSMASQ  
@@ -163,22 +151,20 @@ else
 	$PUBLICBOX_FOLDER/bin/firewall.sh -s
 	log_end_msg $?
 
-	if [ "$IPV6_ENABLE" = "yes" ] && [ "$IPV6_ADVERT" = "radvd" ]
-	then
+	if [ "$IPV6_ENABLE" = "yes" ] && [ "$IPV6_ADVERT" = "radvd" ]; then
 		log_daemon_msg "Starting radvd..."
-		start-stop-daemon --start --quiet --exec radvd  -- -p $PIDFILE_RADVD -C $CONF_RADVD
+		start-stop-daemon --start --quiet --exec /usr/bin/radvd  -- -p $PIDFILE_RADVD -C $CONF_RADVD
 		log_end_msg $?
 	fi
 
-	if [ "$DROOPY_ENABLED" = "yes" ]
-	then
+	if [ "$DROOPY_ENABLED" = "yes" ]; then
 #Start here the PublicBox-Parts droopy i.e.
 		log_daemon_msg "Starting droopy..."
 #Delete 0 Byte Files
 		delete_empty.sh  $UPLOADFOLDER
 		find  $UPLOADFOLDER/ -iname tmp\* -exec rm {} \;
 			DROOPY_USER=""
-		if [ "$DROOPY_USE_USER" = "yes" ] ; then
+		if [ "$DROOPY_USE_USER" = "yes" ]; then
 			DROOPY_USER=" -c $LIGHTTPD_USER:$LIGHTTPD_GROUP "
 		fi
 		DROOPY_DO_CHMOD=""
@@ -192,25 +178,22 @@ else
 
 #Start here the lighttpd i.e.
 	log_daemon_msg "Starting lighttpd..."
-	start-stop-daemon --start --pidfile $PIDFILE_LIGHTTPD --exec /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
+	start-stop-daemon --start --quiet --pidfile $PIDFILE_LIGHTTPD --exec /usr/sbin/lighttpd -- -f $CONF_LIGHTTPD
 	log_end_msg $?
 
 #Start Global Chat daemon if needed.
-	if [ "$GLOBAL_CHAT" = "yes" ]
-	then
+	if [ "$GLOBAL_CHAT" = "yes" ]; then
 		log_daemon_msg "Starting global chat service..."
 		start-stop-daemon -m --start  --background --pidfile $PIDFILE_SHOUTBOX --startas $PUBLICBOX/bin/shoutbox_daemon.sh -- $CONF
 		log_end_msg $?
 	fi
 
 #Start IRC Server
-	if [ "$ENABLE_IRC_SERVER" = "yes" ]
-	then          
+	if [ "$ENABLE_IRC_SERVER" = "yes" ]; then
 		. $CONF_IRC
-		IRC_PARMS="--setuid $IRC_USER --daemon --motd '$IRC_MOTD' "
-		if [ ! -z "$IRC_STATEDIR" ]
-		then
-			IRC_PARMS=" $IRCPARMS --statedir  '$IRC_STATEDIR' "
+		IRC_PARMS="--setuid $IRC_USER --daemon --motd $IRC_MOTD --pid-file $PIDFILE_IRC "
+		if [ ! -z "$IRC_STATEDIR" ]; then
+			IRC_PARMS=" $IRCPARMS --statedir $IRC_STATEDIR "
 		fi
 		log_daemon_msg "Starting Miniircd..."
 		start-stop-daemon $DROOPY_USER -m -S -p $PIDFILE_IRC -x $PUBLICBOX/bin/miniircd.py -- $IRC_PARMS
@@ -219,8 +202,6 @@ else
 fi
 
 $PUBLICBOX/bin/hooks/hook_publicbox_start_done.sh  "$CONF"
-#Start Asterisk PBX
-amportal start
 
 ;;
 stop)
@@ -229,8 +210,7 @@ echo ""
 
 $PUBLICBOX/bin/hooks/hook_publicbox_stop.sh  "$CONF"
 
-if [ "$ENABLE_IRC_SERVER" = "yes" ]
-then
+if [ "$ENABLE_IRC_SERVER" = "yes" ]; then
 	log_daemon_msg "Stopping IRC..."
 	start-stop-daemon -K -q -p $PIDFILE_IRC 
 	log_end_msg $?
@@ -240,29 +220,25 @@ log_daemon_msg    "Removing firewall rules..."
 $PUBLICBOX_FOLDER/bin/firewall.sh -k
 log_end_msg $?
 
-if [  "$USE_APN"  = "yes" ]
-then
+if [  "$USE_APN"  = "yes" ]; then
 	log_daemon_msg  "Stopping hostap... "
 	start-stop-daemon --stop --quiet  --pidfile $PIDFILE_HOSTAPN  --oknodo  --startas "hostapd"
-	log_end_msg  $?
+	log_end_msg $?
 fi
-if [ "$USE_DNSMASQ" = "yes" ]
-then 
+if [ "$USE_DNSMASQ" = "yes" ]; then 
 	log_daemon_msg "Stopping dnsmasq..."
 	start-stop-daemon --stop --quiet  --pidfile $PIDFILE_DNSMASQ  
 	log_end_msg $?
 fi
 
-if [ -e $PIDFILE_RADVD ]
-then
+if [ -e $PIDFILE_RADVD ]; then
 	log_daemon_msg "Stopping radvd..."
 	start-stop-daemon --stop --quite --pidfile $PIDFILE_RADVD
 	log_end_msg $?
 fi
 
 #Stop Global Chat daemon
-if [ "$GLOBAL_CHAT" = "yes" ]
-then
+if [ "$GLOBAL_CHAT" = "yes" ]; then
 	log_daemon_msg "Stopping global chat service..."
 	start-stop-daemon --stop --quiet --pidfile $PIDFILE_SHOUTBOX
 	log_end_msg $?
@@ -272,34 +248,29 @@ fi
 	start-stop-daemon --stop --retry 30 --quiet --pidfile $PIDFILE_LIGHTTPD
 	log_end_msg $?
 
-if [ "$DROOPY_ENABLED" = "yes" ]
-then
+if [ "$DROOPY_ENABLED" = "yes" ]; then
 #Kill Droopy
 	log_daemon_msg "Stopping droopy... "
 	start-stop-daemon --stop --quiet --pidfile  $PIDFILE_DROOPY --oknodo  --startas "python /opt/publicbox/bin/droopy"
 	log_end_msg $?
 fi
 
-if [ "$DO_IFCONFIG" = yes ]
-then
+if [ "$DO_IFCONFIG" = yes ]; then
 	publicbox_setup_wlan.sh $CONF stop
 fi
 
-if [ "$DO_IW" = "yes" ]
-then
+if [ "$DO_IW" = "yes" ]; then
 	iw dev $INTERFACE del
 fi
 
 # REMOVE BRIDGE
-if [ "$DO_BRIDGE" = "yes"  ]
-then
+if [ "$DO_BRIDGE" = "yes"  ]; then
 	log_daemon_msg "Remove Bridge..."
 	BR_CMD="brctl delif  $BRIDGE  $INTERFACE"
 	( $BR_CMD ; )
 	log_end_msg $?
 fi
 
-amportal stop
 
 $PUBLICBOX/bin/hooks/hook_publicbox_stop_done.sh  "$CONF"
 
